---
- name: "Play 1: Network Backup for Cisco IOS"
  hosts: routers:&colo1
  connection: network_cli
  tasks:
    - name: "Task 1: Backup configuration"
      ios_config:
        backup: yes
        backup_options:
          filename: "{{ inventory_hostname }}-running-config.txt"
          #filename: running-config.txt
          #dir_path: /home/bking/network_backups/{{ group_names[0] }}/{{ inventory_hostname }}
          dir_path: /home/bking/network_backups/{{ group_names[0] }}
          #dir_path: /home/bking/network_backups/{{ inventory_hostname }}
